name: Build bananapi_bpi-r4

on:
  schedule:
    - cron: 0 0 * * SAT
  repository_dispatch:
  workflow_dispatch:
    branches:
      - master
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: true
        default: 'false'
        type: choice
        options:
        - true
        - false
      version:
        description: 'OpenWrt version'
        required: true
        default: 'snapshot'
        type: string

env:
  REPO_URL: https://git.openwrt.org/openwrt/openwrt.git
  REPO_BRANCH: openwrt-24.10
  BUILDROOT: ${{ github.workspace }}/openwrt
  CUSTOM_SCRIPT: ${{ github.workspace }}/build_openwrt.sh
  CUSTOM_DIR: ${{ github.workspace }}/patch
  OPENWRT_ISA: aarch64
  OPENWRT_TARGET: mediatek
  OPENWRT_SUBTARGET: mediatek_filogic
  OPENWRT_DEVICE_MODEL: bananapi_bpi-r4
  OPENWRT_CPU_NUMPROC: 4
  OPENWRT_CPU_CFLAG_ARCH: -mcpu=cortex-a53
  OPENWRT_CPU_CFLAG_ARCH_OPTIMIZATION: -mcpu=cortex-a73+crypto+simd+crc
  TZ: UTC

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get -qq update && sudo apt-get -qq upgrade
        sudo apt-get -qq install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget
        sudo apt-get -qq autoremove --purge
        sudo apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"

    - name: Maximize build disk space
      uses: easimon/maximize-build-space@master
      with:
        remove-dotnet: true
        remove-android: true
        remove-haskell: true
        remove-codeql: true
        remove-docker-images: true

    - name: Checkout
      uses: actions/checkout@main

    - name: Download the sources
      run: git clone --branch $REPO_BRANCH $REPO_URL

    - name: Set default target
      run: |
        find ${{ github.workspace }}/patch/ -type f -not -name "*-all.patch" -not -name "*-$OPENWRT_ISA.patch" -not -name "*-$OPENWRT_DEVICE_MODEL.patch" -exec rm {} \;
        rm -f ${{ github.workspace }}/patch/0099-enable-debug-all.patch
        sed -i "s/openwrt_target/$OPENWRT_TARGET/" ${{ github.workspace }}/patch/0002-set-default-target-all.patch
        sed -i "s/openwrt_subtarget/$OPENWRT_SUBTARGET/g" ${{ github.workspace }}/patch/0002-set-default-target-all.patch
        sed -i "s/openwrt_device_model_config/$OPENWRT_DEVICE_MODEL/" ${{ github.workspace }}/patch/0002-set-default-target-all.patch
        if [[ "$OPENWRT_CPU_NUMPROC" -gt 1 ]];then sed -i 's|libustream-openssl|libustream-openssl irqbalance|' ${{ github.workspace }}/patch/0001-target-optimize-all.patch;fi
        sed -i "s/$OPENWRT_CPU_CFLAG_ARCH/$OPENWRT_CPU_CFLAG_ARCH_OPTIMIZATION/" ${{ github.workspace }}/openwrt/include/target.mk
        sed -i "s/OPENWRT_CPU_CFLAG_ARCH_OPTIMIZATION/$OPENWRT_CPU_CFLAG_ARCH_OPTIMIZATION/" ${{ github.workspace }}/patch/0025-musl-cflags-$OPENWRT_ISA.patch
        sed -i 's/-march=mips32r2 -mtune=34kc/'"$OPENWRT_ARCH_OPTIMIZATION"'/' ${{ github.workspace }}/openwrt/target/linux/generic/pending-6.6/308-mips32r2_tune.patch
        sed -i 's/-mno-branch-likely/'"$OPENWRT_CPU_CFLAG_ARCH_OPTIMIZATION"'/' ${{ github.workspace }}/openwrt/target/linux/generic/pending-6.6/302-mips_no_branch_likely.patch
        sed -i "s/CONFIG_NR_CPUS=4/CONFIG_NR_CPUS=$OPENWRT_CPU_NUMPROC/" ${{ github.workspace }}/openwrt/target/linux/mediatek/filogic/config-6.6
        echo "CONFIG_SKB_RECYCLER=y" >> ${{ github.workspace }}/openwrt/target/linux/generic/config-6.6
        echo "CONFIG_SKB_RECYCLER_MULTI_CPU=y" >> ${{ github.workspace }}/openwrt/target/linux/generic/config-6.6
        echo "CONFIG_SKB_RECYCLER_PREALLOC=y" >> ${{ github.workspace }}/openwrt/target/linux/generic/config-6.6
        echo "CONFIG_SKB_RECYCLE_MAX_PREALLOC_SKBS=8192" >> ${{ github.workspace }}/openwrt/target/linux/generic/config-6.6
        echo "CONFIG_SKB_RECYCLE_SIZE=2304" >> ${{ github.workspace }}/openwrt/target/linux/generic/config-6.6
        echo "# CONFIG_SKB_FAST_RECYCLABLE_DEBUG_ENABLE is not set" >> ${{ github.workspace }}/openwrt/target/linux/generic/config-6.6
        sed -i 's/kmod-ath10k-ct[-a-z]*/kmod-ath10k/g' ${{ github.workspace }}/openwrt/target/linux/*/image/*.mk
        sed -i 's/\(ath10k-firmware[-a-z0-9]*\)-ct/\1/g' ${{ github.workspace }}/openwrt/target/linux/*/image/*.mk
        sed -i 's/kmod-ath10k-ct[-a-z]*/kmod-ath10k/g' ${{ github.workspace }}/openwrt/target/linux/*/Makefile
        sed -i 's/\(ath10k-firmware[-a-z0-9]*\)-ct/\1/g' ${{ github.workspace }}/openwrt/target/linux/*/Makefile

    - name: Auto select a specific code revision
      id: autoselect
      if: github.event.client_payload.version == 'stable'
      run: |
        cd $BUILDROOT && git checkout $(git tag --sort=-creatordate | head -n1)
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Manual select a specific code revision
      id: manualselect
      if: github.event.inputs.version != 'snapshot'
      run: |
        cd $BUILDROOT && git checkout ${{ github.event.inputs.version }}
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Load custom
      run: |
        chmod +x *.sh
        $CUSTOM_SCRIPT
        $BUILDROOT/scripts/feeds update -a && $BUILDROOT/scripts/feeds install -a

    - name: Start SSH via tmate
      uses: rdp-studio/ssh2actions@main
      if: github.event.inputs.ssh == 'true'

    - name: Build the firmware image
      id: compile
      run: |
        cd $BUILDROOT && echo "$(($(nproc)+1)) thread compile"
        IGNORE_ERRORS=m make -j$(($(nproc)+1)) defconfig download clean world || IGNORE_ERRORS=m make -j1 defconfig download clean world V=s

    - name: Organize files
      run: |
        tar -zcvf All_Packages.tar.gz $BUILDROOT/bin/packages
        tar -zcvf All_Firmwares.tar.gz $BUILDROOT/bin/targets

    - name: Generate snapshot Release Tag
      id: snapshottag
      run: |
        echo "release_tag=SNAPSHOT_$(date +"%Y-%m-%d")" >> $GITHUB_OUTPUT

    - name: Upload snapshot firmware to Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.snapshottag.outputs.release_tag }}-${{ env.OPENWRT_DEVICE_MODEL }}
        files: |
          All_Packages.tar.gz
          All_Firmwares.tar.gz

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 2
